#let arr = $scripts(->)$

= Définition

Denote $Lambda$ the set of all lambda terms and $arr_beta$ the beta reduction. We define a rewrite system as a couple $(V,E)$ of verticices and $E subset.eq V^2$ the rewrite rules. It's basically an ordered graph. We denote by $C chevron x chevron.r $ the context $C$. We therefore have that $arr_beta$ is the set of couples of the form $ (C chevron.l (lambda x. e ) e' chevron.r, C chevron.l e[x <- e'] chevron.r ) $

Let $Lambda_"I"$ be the set of identity-terms generated by the grammar $l, l' ::= (lambda x. x) | l space l'$. It is a subset of all the lambda terms. One can see that $Lambda_I$ is closed under $arr_beta$, with $arr_beta$ being in this cases couples of the form 
$ (C chevron.l I e chevron.r, C chevron.l e chevron.r) $

Let $cal(L)_"I"$ be the set of words on $Sigma = {A,I}$ generated by the grammar $w, w' ::= I | A w w'$. We define a re-write system $(cal(L)_I,E)$ with re-write rule 
$ w A I w' -> w w' $

*Remark* The set $cal(L)_"I"$ 

*Theorem 1* $(cal(L)_I,E)$ is isomorphic to $(Lambda_I, arr_beta)$

*Proof* Let $Phi : Lambda_"I" --> cal(L)_"I"$ be the bijection defined as
$ 
Phi((lambda x.x)) &= I \
Phi(l l') &= A Phi(l) Phi(l') \
$