#let arr = $scripts(->)$
#let arrr = $scripts(<-)$
#let ORTrees = $bold("ORTrees")$
#let rev = $"rev"$
#let TODO = text(red)[TODO]

#align(center)[#text(size:3em)[Work sheet!]]
#outline()

#pagebreak()

= Introduction 

== Definitions

*General* Define $[k] := {1,...,k}$. Denote $cal(P)(X)$ the set of subset of $X$ and $|X|$ the cardinal of $X$. For $A,B$ two sets, denote $A^B$ the sets of function from $B$ to $A$ and denote $A union.sq B$ the disjoint union of $A$ and $B$. Denote $cal(P)_k (X)$ or $binom(X,k)$ the set of subset of cardinal $k$. Denote by $binom(X,n_1,...,n_k)$ the set of partitions of the form $union.big.sq_(i) A_i = X$ with $|A_i| = n_i$, and by $binom(n,n_1,...,n_k) = |binom([n],n_1,...,n_k)|$. It is well known that $
binom(n,n_1,...,n_k) = (n!)/(n_1 ! n_2 ! ... n_k !)
$

*Graphs* A graph is a $G = (V,E)$ with $E subset.eq cal(P)_2(V)$, and an oriented graph has $E subset.eq V^2$. Both can have multi-graph variants, where every edge $e$ is associated to an arity $\#(e) in NN^*$. For $T = (V_T,E_T,r)$ a rooted tree, denote $T(x)$ the subtree tree rooted at $x$, and by $|T|$ the number of nodes in $T$. For $G$ a graph, denote $deg v$ the degree of $v$ and if $G$ is oriented, denote $deg^+ v$ the outgoing degree and $deg^- v$ the ingoing degree. If $G$ is a multi-graph, the degree is the sum of the arities. For $S subset.eq V_G$, denote by $G[S]$ the (multi)graph induced on $S$. If $G$ is a multi-graph, denote $overline(G)$ the same graph where all arities is $1$, i.e. the regular graph behind $G$. A _path_ is a sequence of vertices $chevron v_1,...,v_k chevron.r$ with $forall i < k, \#(v_i,v_(i+1))>=1$ and a _co-path_ is a sequence of vertices $chevron v_1,...,v_k chevron.r$ with $forall i < k, \#(v_(i+1),v_i)>=1$

*Grammars* For $cal(G)$ a grammar, denote $cal(G) chevron chevron.r$ the set of contexes over $cal(G)$. For $C$ a context denote $C chevron N chevron.r$ the context where the hole has been replaced with $N$.

*$lambda$-calculus* Denote $Lambda$ the set of all lambda terms and $arr_beta$ the beta reduction. Denote $I := (lambda x.x)$ the identity $lambda$-term. All lambda term will be considered up to $alpha$-equivalence. We therefore have that $arr_beta$ is the set of the form $ C chevron.l (lambda x. e ) e' chevron.r arr_beta C chevron.l e[x <- e'] chevron.r $

*Identity Terms* Let $Lambda_I$ be the set of identity-terms generated by the grammar $e, e' ::= (lambda x. x) | e space e'$. It is a subset of all the lambda terms. One can see that $Lambda_I$ is closed under $arr_beta$, with $arr_beta$ being in this case of the form 
$ C chevron.l I e chevron.r arr_beta C chevron.l e chevron.r $

*Rewrite systems* A rewrite system $R = (V,arr)$ is an oriented multi-graph with $E_G = (->)$. Nodes $v in V$ such that $deg^+ v = 0$ are called _final nodes_ or _normal forms_, and nodes such that $deg^- v = 0$ are call initial nodes. A path $(p_1,...,p_n)$ in $G$ is called a reduction sequence and is noted $p_1 -> p_2 -> ... -> p_n$ or $p arr^n p_n$. We denote by $arr^*$ the transitive reflexive closure of $->$. For $R$ a rewrite system, we have $->$.

Two systems $(V_1,E_1)$ and $(V_2,E_2)$ are said to be isomorphic if there exists a bijection $Phi : V_1 --> V_2$ such that $(x,y) in E_1 <=> (Phi(x),Phi(y)) in E_2$ and that $Phi$ preserve the arity. We will denote this by $(V_1,E_1) equiv (V_2,E_2)$


== Rewrite system of interest (TO-REDO)

We denote $ORTrees$ the set of rooted tree were children are ordered from left to right (min to max or 1 to $n(T)$). Such a tree can be represented using a finite $V_T subset.eq NN^*^omega$ closed under prefixes and such that if $u beta in V_T$ then $forall alpha < beta, u alpha in V_T$. In that case, $max {alpha in NN| u alpha in V_T}$ is the number of children of the subtree $u^(-1) T$. For $T$ a tree we denote $n_T$ the number of children of the root. We can also write $N(x_1,...,x_n)$ the tree with children $x_1,...,x_n$.

#let Tree = math.op([*Tree*])
We will study the identity rewrite system $(Lambda_I, arr_beta)$

*Tree rewrite system* Define $Tree$ the set of all unlabeled rooted trees of unbounded degree but an order on their children (let's say, left to right). We say that $T arr_l T'$ if there is a leaf $u in V_T$ such than $T - u = T'$. Denote this system as $(Tree, arr_l)$



*Theorem* $(Lambda_I, arr_beta) equiv (Tree, arr_l)$


*Proof* Given a lambda term $M$, we associate $Phi(M)$ a tree by induction :
- If $M = I$, let $Phi(M)$ be a single root with no children
- Otherwise, decompose $M = u_1 space (u_2 space (u_3 space (....(u_d space I))))$, and let $Phi(M)$ be the tree with a root $r$ and children the trees $Phi(u_1),Phi(u_2),...,Phi(u_d)$

Then if $M = C chevron I x chevron.r arr_beta C chevron x chevron.r = N$, then in the decomposition, both $I$ and $x$ are children of the same root in $Phi(M)$. So we removed a leaf in $M$, $x$ went from the $(i+1)$-th children to the $i$-th, and all is good. *TODO BETTER*

Reciprocly, if we remove a leaf, then it is one of the $u_i$ of a node, and since it can't be the last $I$ as it isn't part of the mapping, nice. *TODO BETTER*

== Properties

$arr_l^*$ is an order relation over $Tree$. It is not a WQO: for all $n in NN$, define
- For $T_0 = ((()),(()))$
- For $n>1, T_(n+1) = ((),((T_n)))$

Then ${T_n : n in NN}$ is an infinite anti-chain.

*Prop* We have $T arr_l^* T'$ iff $T = (A_1,..,A_k)$ and $T' = (B_1,...,B_k')$ such than there exists an injection $sigma : [k'] --> [k]$ such than $forall i <= k', A_(sigma(i)) arr_l^* B_i$

*Higman* $(Tree,arr_l)$ is just the fixpoint of higman lemma...



#let DAG = math.op("DAG")
*Generated DAG* For $T in Tree$, define $DAG(T)$ the (multigraph) rewrite system $Tree[S]$ with $S = {T' in Tree | T arr_l^* T'}$.

A few questions of interest are:
- Given a $T$, how many way can we reduce it to the empty tree? (Part 1 on counting)
- Can we find a polynomial simple  equivalence $equiv$ such than $T equiv T' => DAG(T) <=> DAG(T')$ (Part 2)
- What about $T equiv T' <=> DAG(T) <=> DAG(T')$ ? (Part III, categorical aspect)
- Given $G = DAG(T)$ unlabelled, can we recover $T$ ?


*Prop*
- If we are given an unoriented $G$ :
  - Either it is a path with all edges of the same arity 1, and $T$ was a path of the same length
  - Either we can recover the final node $T$ as the only vertex of degree 1. 
- Therefore, given an oriented $G$ that isn't a path, we can recover the order of $G$ by the distance to the final node as $DAG(T)$ is always a stratified graph. Therefore we can recover the root.
- Given an ordered $G = DAG(T)$, denote $p_1,..,p_k$ the longuest co-path to the final node, such that $forall i<= k,deg^+ p_i = 1$. Then $k = h(T)$, the height of $T$

*Prop* Let $T in Tree$ and $x in V_T$. Then $DAG(T)[V_(T(x))] = DAG(T(x))$

#pagebreak()
= Counting

For $T$ a tree, denote $N(T)$ the number of way to reduce it into a leaf, so that $N(T)$ is the number of path from $T$ to the empty tree, counting the multi-edges. Such a path is called a _reduction sequence_ and is represented by a sequence $chevron x_1,...,x_n chevron.r$ of vertices of $T$ such than $x_i$ is a leaf in $T[{x_(i+1),...,x_n}]$. $x_i$ represent morally the $i$-th node to be removed.

*Theorem* For all trees $T$, we have $ N(T) = (|T|!)/(product_(x in V_T) |T(x)|) $


*Proof* By induction on $|T|$. If $|T| = 1$, then there is one way, that is to remove the only node / leaf. Let us consider a tree $T$ with $|T| = n+1$. Denote the root $r$ and the direct children of the root as $x_1,...,x_d$. Let's us fist count the number of path of $T$ in function of $(N(T(x_i)))_i$:

For all $i<= d$, let $p^((i))$ be a reduction sequence of $A_i$. Remark that for all $i in [d]$ we have $|p^((i))| = |A_i|$. For every partition $X_1 union.sq ... union.sq X_d$ of $[ n ]$ such that $|X_i| = |A_i|$ we can create the reduction sequence $p = chevron p_1,...,p_n chevron.r$ defined by induction by letting $p_(i)$ be the next element in $p^((j))$ such that $i in X_j$ (unique because it is a partition). By appending the root to $p$, we obtain a reduction sequence of $T$.

So for every $d$-uplet of reduction sequence of each children and each partionning of $[n]$ respecting the number of edges of each subtree, we can obtain a reduction sequence. This is a bijective mapping. Let $p$ be a reduction sequence. It ends with $r$, so let's ignore this node. We can extract the subsequence $p^((i))$ from splitting $p_i$ in function of which nodes occurs in which $T(x_i)$. This gives us both the partition and the set of subsequences.

We therefore arrive at this formula :

$ N(A) 
&= binom(n-1,|A_1|,...,|A_k|) product_(i=1)^k F(A_i) 
$

Then for every $i <= d$, $|T(x_i)| <= n$ so we can apply the induction hypothesis to every $T(x_i)$. Denote $n_i = |T(x_i)|$, we have :
$ 
N(T) 
&= binom(n-1,n_1,...,n_d) product_(i=1)^k F(T(x_i)) \
&= (n-1)!/(n_ 1!...n_k !) product_(i=1)^k (n_i !)/(product_(x in T(x_i)) |T(x_i)|) \
&= (n-1)!/(product_(i=1)^k product_(x in T(x_i)) |T(x_i)|)  \
&= (n-1)!/(product_(x in V_T \\{r}) |T(x_i)|) &union.big.sq_(i<= d) T(x_i) "is a partition of" V_T \\{r}\
&= n!/(product_(x in T) |T(x_i)|) 
$


*Long chain*
#let LC = math.op("LC")
Define inductively the set of long chains of $M in Lambda_I$ as $LC(I) = emptyset$ and for $M != I$, it can be uniquely written as 
$ M = u_1 space (u_2 space (u_3 space (....(u_d space I)))) $
and define $LC(M) = {(u_1,...,u_d)} union union.big_(i<= d)LC(u_i)$

*Corollary* For $M in lambda_I$ a identity-term, denote $|M|_I$ the number of $I$ in $M$. Then the number of way to reduce $M$ to its normal form $I$ is $ (|M|_I !)/(product_((u_1,...,u_d) in LC(M)) (1+sum_(i<= d) |u_i|_I ) ) $






#pagebreak()

= Dyslexic trees

Denote by $T equiv T$ the fact that two left-to-right rooted trees are the same (aka same dyck words, aka same identity-term).

For a fixed $P subset.eq NN$, we define a tree transformation $rho_P^i (T)$ with $i$ the height by induction  :
$
rho_P^i(l) &= l " for " l " a leaf" \
rho_P^i (N(x_0,...,x_n))
  &= N(rho_P^(i+1) (x_n),...,rho_P^(i+1) (x_0)) " if " i in P \
rho_P^i (N(x_0,...,x_n))
  &= N(rho_P^(i+1) (x_0),...,rho_P^(i+1) (x_n)) " if " i in.not P
$

We define the equivalence relation $T prop T' <==> exists P subset.eq NN, rho^0_P (T) = T'$. It is an equivalence relation as taking the xor (symetric difference) of two $P$ would work, and the same $P$ work for $T' prop T$. For $T prop T'$, there is an isomorphism as rooted unordered tree $phi_T^P : V_T <--> V_(T')$. We will omit $P$ and $T$ when it's clear from context. $rho$ is an operation on TREES while $phi$ is the operation on vertices of a fixed tree. We can see that $T equiv T' => rho_P (T) equiv rho_P (T')$ as it is a function defined on rooted ordered trees. 

*Lemma* $rho_P^i$ is an involution.

*Proof* By induction on the tree. The leaf case is trivial. For $T = N(x_0,...,x_n)$, if $i in P$, then
$
rho_P^i (T) = N(rho_P^(i+1)(x_n),...,rho_P^(i+1)(x_0)).
$
Applying $rho_P^i$ again reverses the order once more, and by induction each $rho_P^(i+1)(rho_P^(i+1)(x_j)) = x_j$. Hence we get back $N(x_0,...,x_n)$. The case $i in.not P$ is identical but without the reversal of the node itself. Therefore $rho_P^i compose rho_P^i = id$.

*Subtrees* If $S subset.eq V_T$ is connected and contains the root, then $T[S]$ is an induced subtree. Denote $cal(S)(T)$ the sets of such connected subset containing the root. Morally, we removes iteratively all the leafs outside of $S$. Notice that $S |-> T[S]$ is not always injective.

*Naturality Lemma* Let $T$ be an ordered tree and $S in cal(S)(T)$, then $ forall P subset.eq NN, forall i in NN, space rho^i_P (T)[ phi_P^T (S) ] equiv rho_P^i (T[S]). $

*Proof* By induction on $T$. If $T = l$ is a leaf, then necessarily $S = V_T$, hence $rho_P^i (T)[phi_P^T (S)] = l = rho_P^i (T[S]).$

Suppose now $T = N(x_0,...,x_n).$ For every $0 <= i <= n$, let $S_i = S inter V_(x_i).$ Since $S$ is connected and contains the root, every $S_i$ is either empty or belongs to $cal(S)(x_i)$. Assume first that $0 in.not P$. Then $rho_P^0(T) = N( rho_P^1(x_0),..., rho_P^1(x_n))$.

Restricting to the vertices of $phi_P^T (S)$ keeps exactly the children corresponding to non-empty $S_i$. Therefore
$
rho_P^0 (T)[phi_P^T (S)]
=
N( (rho_P^1(x_i)[phi_P^(x_i)(S_i)] )_i ).
$

By induction hypothesis, we have for each $i$ the fact that $rho_P^1(x_i)[phi_P^(x_i)(S_i)] equiv rho_P^1(x_i [S_i]).$ Hence, since the root is in $S$ and not in $P$
$
rho_P^0(T)[phi_P^T (S)] equiv N(( rho_P^1(x_i [S_i]) )_i) equiv rho_P^0 (N((x_i [S_i])_i)) equiv rho_P^0(T[S]).
$

The case $0 in P$ is identical, except that both sides reverse the order of the children simultaneously: we have
$
rho_P^0 (T)[phi_P^T (S)]
=
N( (rho_P^1(x_(n-i))[phi_P^(x_(n-i))(S_i)] )_i ).
$
and therefore
$
rho_P^0(T)[phi_P^T (S)] equiv N(( rho_P^1(x_(n-i) [S_(n-i)]) )_i) equiv rho_P^0 (N((x_i [S_i])_i)) equiv rho_P^0(T[S]).
$
*Corollary* For all $S,S' in cal(S)(T)$ such than $T[S] equiv T[S']$, we have
$ forall P subset.eq NN, space rho^0_P (T)[phi_P^T (S)] equiv rho^0_P (T)[phi_P^T (S')] $
This is because since $T[S] equiv T[S']$ then $rho^0_P (T[S]) equiv rho^0_P (T[S'])$ so we have by the naturality $ rho^0_P (T)[phi_P^T (S)] equiv rho_P^0 (T[S]) equiv rho_P^0 (T[S']) equiv rho^0_P (T)[phi_P^T (S')]. $

*Theorem* If $T prop T'$, then $DAG(T) equiv DAG(T')$.

*Proof* Suppose $rho^0_P (T) = T'$. Define the isomorphism :
$
Phi : DAG(T) &<--> &DAG(T') \
T[S] &mapsto.long &rho^0_P (T[S])
$

This is well-defined by the naturality lemma. Since $rho_P^0$ is an involution, the same construction applied from
$T'$ to $T$ gives the inverse map, hence $Phi$ is bijective.

Now we show that $Phi$ preserves edges. Since $Phi$ is involutive, we just need to proove that if $A_1 -> A_2$ is an edge in $DAG(T)$ with multiplicity $m$, then $Phi(A_1) -> Phi(1_2)$ is an edge in $DAG(T')$ with multiplicity $m' >= m$.

Suppose that there is an edge $A_1 -> A_2$ in $DAG(T)$ with multiplicity $m$. Then there is $m$ ways to write $A_1 equiv T[S],A_2 equiv T[S']$ where $S' = S - {l}$ for some leaf $l$ of $T[S]$. Denote $M$ the set of couples $(S,l)$ such than $A_1 equiv T[S]$ and $A_2 equiv T[S \\ {l}]$.

Let $(S,l) in M$. Because $phi$ is a rooted tree isomorphism, $phi(l)$ is a leaf of $T'[phi(S)]$. Also, $phi(S \\ {l}) = phi(S) - {phi(l)}$. Therefore there is an edge $T'[phi(S_1)] -> T'[phi(S_2)]$. It remains to check multiplicities. 

Consider the map $gamma :(S,l) |-> (phi(S), phi(l))$. It is injective as $phi$ is. So edge multiplicities are preserved.

Therefore $DAG(T) equiv DAG(T'). square$

#pagebreak()

= Categorical aspect


*Subtrees* If $S subset.eq V_T$ is connected and contains the root, then $T[S]$ is an induced subtree. Denote $cal(S)(T)$ the sets of such connected subset containing the root. Morally, we removes iteratively all the leafs outside of $S$. Notice that $S |-> T[S]$ is not always injective.

Let's define the category $ORTrees$ whose objects are Ordered (left-to-right) Rooted Trees. We'll denote the root as $r$. We define the morphisms $ORTrees(T,T') = {S in cal(S)(T) | T[S] equiv T'}$. We say that a morphism $S in ORTrees(T,T')$ is elementary if $|V_T - S| = 1$ (aka we only remove a single node, a leaf)

*Remarks*
- There is a terminal object, the tree with only a root, with only morphisms $S = {r}$

*Theorem* Let $F : ORTrees --> ORTrees$ be an equivalence of categories. Then
$
  F(T) equiv T' => DAG(T) equiv DAG(T').
$

*Remark* The previous case was just $F(T) = rho_P (T)$ and $F(T ->_S T') = rho_P (T) -->_(phi_P (S)) rho_P (T')$ 

*Proof.* Since $F$ is an equivalence of categories, it is fully faithful and essentially
surjective. In particular, for all trees $A,B$, the map
$
  F_(A,B) : ORTrees(A,B) --> ORTrees(F(A),F(B))
$
is a bijection. We can define $Phi : DAG(T) --> DAG(F(T))$ as $Phi(T') = F(T')$ : it is indeed a application into $"DAG"(T)$ as for all $A in DAG(T)$, we have a morphism $T -->_S A in ORTrees(T,A)$, so a morphism $F(T) -->_(F(S)) F(A) in ORTrees(F(T),F(A))$, so $A in DAG(F(T))$.

Conversely, because $F$ is an equivalence, it has a quasi-inverse $G$. Applying
the same argument to $G$, every vertex of $DAG(T')$ is equivalent to some
$F(A)$ with $A$ a vertex of $DAG(T)$. Hence $Phi$ is a bijection on vertices,
up to $equiv$.

It remains to prove that $Phi$ preserves edges and their multiplicities. This is because a morphism $f : A --> B$ removes exactly one leaf if and only if $f$ is
non-invertible and irreducible (A simple cardinality argument on $S$ in $A -->_S B$ for both ways). Since equivalences of categories preserve and reflect isomorphisms, factorisations,
and irreducibility, every distinct edge of $DAG(T)$ is sent to a distinct edge $F(A) --> F(B)$ of $DAG(T')$. Thus edge multiplicities are preserved.

So $Phi : A |-> F(A)$ induces an isomorphism of directed multigraphs and we have
$
  DAG(T) equiv DAG(T').
$
$square$

*Questions!*
- Are all equivalences of categories $F : ORTrees --> ORTrees$ of the form $rho_P$ ?
- If $Psi : ORTrees --> ORTrees$ preserve the DAGs, is it necessary an equivalence of categories? Or can we lighten the hypothesis?

If both questions are yes, we have an iff with $scripts(prop)_P$. If the first is no, we should be able to get a bigger equivalence relation than $scripts(prop)_P$. If the second is false (it probably is), can we get a bigger equivalence using a $Psi$ that isn't an equivalence of categories?

#pagebreak()

= Reciprocity OMMG!!!!


For $T in ORTrees$, define :
- $h(T)$ its height
- $|T|$ the number of vertexes
- $n(T)$ the number of children of the root
- $l(T)$ the number of children that are leafs of the root

We note $l$ the leaf. The $DAG(T) = (V,E)$ is with multiplicity and for $e in E$ denote $\#(e)$ the arity of the arc $e$. For every $i <= n$ we define $E_i = N(l,l,...,l)$ the tree with $i$ leafs and $P_i = N(N(...N(l)...))$ the path of length $i$.

*DAG Reconstruction Lemma.* Let $T,T' in ORTrees$ be such that  $DAG(T) equiv DAG(T')$ and write $T = N(x_1,...,x_n),$ and $T' = N(y_1,...,y_m).$ Then:
1. $n = m$, $h(T) = h(T')$, $|T| = |T'|$ and $l(T) = l(T')$
2. There exists $theta : [n] --> [n]$ such that for every $i in [n], DAG(x_i) equiv DAG(y_(theta(i)))$

*Proof.* Denote $Psi : DAG(T) <--> DAG(T')$ the DAG isomorphism. For $u,v in V_T$ define $u prec.eq v$ iff $u$ is below $v$ in the DAG (aka if there is a path from $v$ to $u$).

Notice that we can find the position of all the $(E_k)_(k<n_T)$ that are in the DAG : $E_1 = P_1$ is the only element above the final node, and for every $i$ we have that $E_(i+1) arr_(i+1) E_(i)$ is the only edge of arity $i+1$ into $E_i$. That is because if you have another edge into $E_i$, then it is of the shape $N(l,l,...,l,N(l),l,...)$ with only an arity of $1$ into $E_i$. Therefore $Psi(E_i) = E_i$. 

Similarly, there is only one path maximal in length of out-degree $1$ into the root, corresponding to the sequence $P_i -> ... -> P_1 -> l$ in the $DAG$ with $P_i in DAG(T)$ the path-tree of length $i$.

We then show that for every node $t in DAG(T)$, we can find $h(t)$, $|t|$ and $n_t$ only using the dag structure (i.e. they are $Psi$-preserving): 
- $|t|$ is the depths of $t$ in $DAG(T)$ as every traversed edge into the normal form remove exacly one node.
- $n(t) = max {i in NN | E_i prec.eq t }$ as $t arr^* E_i$ iff $t = N(x_1,...,x_i,x_(i+1),...)$ iff $n(t) >= i$.
- $h(t) = max {i in NN | P_i prec.eq t }$ for the same reason.
- For $l(t)$, consider the multiset of arcs with multiplicity $A_t := {(t,u) in DAG(T) | n(u)<n(t)}$. Every arc of this form correspond to a reduction of a leaf of $t$ at the root, therefore $sum_(e in A_t) \#(e) = l(t)$.

Therefore for $t = T$ and $t' = T'$ the root of both dags we have the first point of the reconstruction lemma. Now, write $T = N(x_1,...,x_n)$ and $T = N(y_1,...,y_n)$. We can map every leaf of $T$ into a leaf of $T'$, so let's define the mapping for every non-leaf child of $T$. For every child $x_i$ that is not a leaf define
$ T_i := N(x_1,...,x_(i-1),l,x_(i+1),...,x_n). $

First, let's show that that ${T_i : i <= n} = max { t in DAG(T) | l(t) = l(T)+1 and n(t) = n(T)}$ (the set of maximum elements for $prec.eq$ in ${ t in DAG(T) | l(t) = l(T)+1 and n(t) = n(T)}$) (the condition $n(t) = n$ should be useless but anyway):
- $==>$: Suppose $T_i$ not maximal in ${ t in DAG(T) | l(t) = l(T)+1 and n(t) = n(T)}$, then there exists $t in DAG(T)$ with $l(t) = l(T)+1$ and $(t -> T_i) in DAG$. Consider the leaf being removed from $t$ : it cannot be at the root as $l(t) = l(T_i)$ but it cannot be in a $x_j$ for $j != i$ as all other values $x_j$ in $T_i$ are already maximal in $T$.
- $<==$: Let $t in max { t in DAG(T) | l(t) = l(T)+1 and n(t) = n(T)}$. Write $t = N(t_1,...,t_n)$. First, if there is two elements such that $t_i != x_i$ and $t_j != x_j$, they can't both be leafs as $l(t)$ only decreased by one. Without loss of generality, assume $t_i != l$. We can just set $t_i <- x_i$ and we have a bigger element that still respect the condition. So, without loss of generality, only one $t_i != x_i$, and if it isn't a leaf, $l(t) = l(T)$, so $t = T_i$

Therefore ${T_i : i <= n}$ is preserved under DAG-isomorphism as it can be defined only using $prec.eq$, $l(t)$ and $n(t)$. For every $T_i$, consider the sub-DAG from $T_i$ to $T$ define by $[T_i,T] := arrow.t T_i = { A in DAG(T) | T_i <= A }$. We will prove that $DAG(x_i) equiv [T_i,T]$ (morally, this is beacause the only part that can move is the $i$-th component since all the other ones are maximals already). Define the isomorphism $phi : DAG(x_i) <--> [T_i,T]$ by $phi(u) = N(x_1,...,x_(i-1),u,x_(i+1),...,x_n)$. $phi$ is a bijection by definition of $[T_i, T]$ and $(u arr v) in DAG(x_i) <=>(phi(u) -> phi(v)) in [T_i, T]$.

Finally, to define $theta$, just do as such :
- Map every leaf child of $T$ to a leaf of $T'$ (possible since $l(T) = l(T')$)
- For all non-leaf child, map $x_i$ to the $y_j$ such that $T_j = Psi(T_i)$ : Since all $(T_i)_i$ are preserved under DAG, we have that $Psi$ is a bijection between $(T_i)_i$ and $(T'_i)_i$, and since $Psi$ preserves DAG isomorphism, we finally have $Psi(DAG(x_i)) equiv Psi([T_i, T]) equiv [Psi(T_i), T'] equiv DAG(Psi(x_i))$. $square$




#pagebreak()

= Reciprocical (try 3, WIP)

We define $T[S]$ the induced tree on $S$, formally by $T[S] = arrow.b S union arrow.t S$. Denote $[n] = {1,...,n}$.

*Coherence Dyslexic Relation* We define by induction for $T,T' in ORTrees$ and $phi : V_T <--> V_(T')$ a bijection the coherent dyslexic relation $T scripts(prop)_phi T'$ by
- *Base case:* $l scripts(prop)_phi l$ for $l$ the leaf and $phi$ defined by $phi(epsilon) = epsilon$
- *$"Id"$ case:* We define $T = N(x_1,...,x_n) scripts(prop)_phi T(y_1,...,y_n)$ if $forall i <= n, x_i scripts(prop)_(phi_i) y_i$, $phi(i :: u) = i ::phi_i (u)$ and $phi(epsilon) = epsilon$, and if for every pair $i,j in [n]$ and $(S, S') in cal(S)(x_i) times cal(S)(x_j)$ we have:
$ x_i [S] equiv x_j [S'] <==> y_i [phi_i (S)] equiv y_j [phi_j (S')] $
- *$"Rev"$ case:* We define $T = N(x_1,...,x_n) scripts(prop)_phi T(y_1,...,y_n)$ if $forall i <= n, x_i scripts(prop)_(phi_i) y_(n-i+1)$, $phi(i :: u) = (n-i+1) :: phi_i (u)$ and $phi(epsilon) = epsilon$, and if for every pair $i,j in [n]$ and $(S, S') in cal(S)(x_i) times cal(S)(x_j)$ we have:
$ x_i [S] equiv x_j [S'] <==> y_(n-i+1) [phi_(i) (S)] equiv y_(n-j+1) [phi_(j) (S')] $

We note $T prop T'$ if there exist a $phi$ such than $T scripts(prop)_phi T'$.

*Equivalent Definition* For every $n in NN$, define $Theta_n = {id_n ; rev_n}$. We have the following equivalent definition. For two trees
$T = N(x_1,...,x_n), quad T' = N(y_1,...,y_n),$ then define $T scripts(prop)_phi T'$ if there exists $theta in Theta_n$ and bijections $phi_i : V_(x_i) <--> V_(y_(theta(i)))$
such that:
1. For every $i in [n]$, $x_i scripts(prop)_(phi_i) y_(theta(i));$
2. The global bijection $phi : V_T <--> V_(T')$ is defined by
$ phi(epsilon) = epsilon; quad phi(i :: u) = theta(i) :: phi_i (u) $
3. For every $i,j in [n]$ and every $S in cal(S)(x_i), S' in cal(S)(x_j),$ we have
$
x_i [S] equiv x_j [S'] <==>
y_(theta(i))[phi_i(S)] equiv y_(theta(j))[phi_j(S')].
$

*Prop* We have $T prop T'$ that is a equivalence relation.
- *Reflexivity:* We show that for every $T$, we have $id_T$ such than $T scripts(prop)_(id_T) T.$ If $T = l$ is a leaf, this is exactly the base case.

  Now suppose $T = N(x_1,...,x_n).$ By induction, for every $i in [n]$, we have $x_i scripts(prop)_(id_(x_i)) x_i.$. We apply the *Id* case with $id_T (epsilon) = epsilon, quad id_T (i :: u) = i :: id_(x_i)(u) = i :: u.$ It remains only to check coherence, but it is immediate as $id_(x_i)(S) = S$ and $id_(x_j)(S') = S'$, so for every $i,j,S,S'$,
  $ x_i [S] equiv x_j [S'] <==> x_i [id_(x_i)(S)] equiv x_j [id_(x_j)(S')]. $
- *Symmetry:* Assume $T scripts(prop)_phi T'.$ Write $T = N(x_1,...,x_n)$ and $T' = N(y_1,..., y_n)$. Then we have
  $  $
- *Transitivity:* Trust me bro

*Global Coherence Lemma.* If $T scripts(prop)_phi T'$, then for every $S,S' in cal(S)(T)$,
$
T[S] equiv T[S'] <==> T'[phi(S)] equiv T'[phi(S')].
$

*Proof.* First, the root arity of a vertex $A$ is visible inside $DAG(A)$. 

Now consider the maximal vertices below $T$ whose root arity is $k$. These are exactly the full root-subwords
$
N(x_(i_1),...,x_(i_k))
quad
(1 <= i_1 < ... < i_k <= n).
$
This property is internal to the DAG: root arity is internal, and maximality is with respect to the order $->^*$.

Therefore an isomorphism
$
D(T) equiv D(T')
$
sends the family of full root-subwords of $T$ to the family of full root-subwords of $T'$.

In particular, for $k = n - 1$, the isomorphism sends the one-deletion deck
$
N(x_1,...,hat(x_i),...,x_n)
$
to the one-deletion deck of
$
N(y_1,...,y_n).
$

The intersections of these cards recover the betweenness relation on the root positions. Hence the induced map on positions is either order-preserving or order-reversing. Thus there exists
$
theta in {id_n, rev_n}.
$

For each $i$, the child $x_i$ is recovered as the factor missing from the corresponding card. Equivalently, its whole reduction DAG is the principal factor between the full root-subword containing $x_i$ and the same root-subword with $x_i$ reduced. Since the DAG isomorphism preserves these principal factors, we get
$
D(x_i) equiv D(y_(theta(i))).
$


*Theorem* We have $T prop T' <=> DAG(T) equiv DAG(T')$

#pagebreak()
= Reciprocity (try 2)


#let ORTrees = $bold("ORTrees")$
We denote $ORTrees$ the set of rooted tree were children are ordered from left to right (min to max or 1 to $n_T$). Such a tree can be represented using a finite $V_T subset.eq NN^*^omega$ closed under prefixes and such that if $u beta in V_T$ then $forall alpha < beta, u alpha in V_T$. In that case, $max {alpha in NN| u alpha in V_T}$ is the number of children of the subtree $u^(-1) T$. For $T$ a tree we denote $n_T$ the number of children of the root. We can also write $N(x_1,...,x_n)$ the tree with children $x_1,...,x_n$.

We define $T[S]$ the induced tree on $ S$, formally $T[S] = arrow.b S union arrow.t S$. Denote $[n] = {1,...,n}$.

Let $sigma = (sigma_T : [n_T] <--> [n_T])_(T in ORTrees)$ be a familly of bijections of the childrens. We define $sigma(T)$ as applying $sigma$ to every subtree of $T$:
- $sigma(l) = l$ for $l$ a leaf.
- For $T= N(x_1,...,x_n)$ we define
$ sigma(N(x_1,...,x_n)) = (sigma(x_(sigma_T^(-1) (1))),sigma(x_(sigma_T^(-1) (2))),...,sigma(x_(sigma_T^(-1) (n)))). $

For $(sigma_T)_(T in ORTrees)$ such a familly of bijection, define the isomophism $phi_sigma^T : V_T <--> V_(sigma(T))$ as (assuming we represent a $V_T$ as a set of path) :
- $phi_sigma^T (epsilon) = epsilon$
- For $T = N(x_1,...,x_n)$, let $phi_sigma^T (i :: q) = sigma_T (i) :: phi_sigma^(x_i) (q)$ (valid since $q in V_(x_i)$)

A familly $(sigma_T)_T$ is said to be _frontier-preserving_ if for all
$T in ORTrees$ and every prefix-antichain $A subset.eq V_T$,
$
  sigma(T)[phi_sigma^T (A)] = sigma(T[A]).
$


A familly is said to be _subtree-preserving_ if for all tree $T in ORTrees$ we have
$ forall S subset.eq V_T, #h(10pt) sigma(T)[phi_sigma^T (S)] = sigma(T[S]) $

Denote $T scripts(prop)_sigma T'$ if $sigma(T) = T'$. Denote $T prop T'$ if there exists $(sigma_T)_T$ subtree-preserving such that $T scripts(prop)_sigma T'$.

*Lemma* If $(sigma_T)_T$ is _frontier-preserving_, then it is
_subtree-preserving_.

*Proposition* $prop$ is an equivalence relation on $ORTrees$.

*Theorem* Let $T,T' in ORTrees$, $DAG(T) equiv DAG(T') <==> T prop T'$

#pagebreak()

= (Not Working previous version) Dyslexic trees

Denote by $T equiv T$ the fact that two left-to-right rooted trees are the same (aka same dyck words, aka same lambda term).

We say that $T, T'$ two trees with respective roots $r,r'$ are _dyslexic trees_ if there exists an isomorphism $phi : V_T <--> V_T'$ such than $phi(r) = r'$ and for all node $x = (x_0,...,x_k) in V_T$ and $x' = (x'_0,...,x'_k) in T'$, we have $forall i, phi(x_i) = x'_i$ or $forall i, phi(x_i) = x'_(k-i)$. We denote it $T prop_phi T'$.

By induction, we can easely see that $T prop T'$ iff
- either $T = T'$ the leaf (case1)
- either $T=x(x_0,...,x_n)$ and $T' = x'(x'_0,...,x'_n)$ with $forall i <= n, x_i prop x'_i$ (case 2)
- either $T=x(x_0,...,x_n)$ and $T' = x'(x'_0,...,x'_n)$ with $forall i <= n, x_i prop x'_(n-i)$ (case 3)

*Lemma* if $S subset.eq V_T$ is connected and contain the root, then $T[S]$ is an induced subtree. Denote $cal(S)(T)$ the sets of such $S$. Morally, we removes iteratively all the leafs outside of $S$.

*Lemma* Let $S,S' in cal(S)(T)$. We have $S' = S \\{l}$ with $l$ a leaf of $T[S]$ iff $T[S] arr T[S']$.

*Lemma* If $T prop_phi T'$ then $forall S,S' in cal(S)(T)$, if $S subset.eq S'$ then $phi(S) subset.eq phi(S')$. 

*Lemma* If $T prop_phi T'$ then $forall S in cal(S)(T)$, $phi(S) in cal(S)(T')$. More generally, $phi : cal(S)(T) <--> cal(S)(T')$ is an isomorphism for $subset.eq$.

*Lemma* If $T prop_phi T'$ then $forall S in cal(S)(T), T[S] prop T'[phi(S)]$

*Prop* If $T prop_phi T'$, then $DAG(T) equiv DAG(T')$.

*Proof* We define the isomorphism. The hard part is the injectivity :
$
Phi : DAG(T) &<--> &DAG(T') \
T[S] &mapsto.long &T'[phi(S)]
$

- *Edges $=>$* Suppose that $e = (A_1, A_2) in DAG(T)$. We can write $A = T[S_1]$ and $A_2 = T[S_2]$ with $S_2 = S_1 \\ {l}$, with $l$ a leaf of $T[S_1]$. Then since $|phi(S_1)| = |S_1| = |S_2|+1 = |phi(S_2)|+1$, and $phi(S_2) subset.eq phi(S_1)$, we can write $phi(S_2) = phi(S_1) \\ {l'}$. $l'$ is a leaf as $phi(S_2)$ is always connected.
- *Edges $<=$* Same, roles of $T$ and $T'$ are totally symmetric here.
- *Surjectivity* Let $T'[S] in DAG(T')$. Then $Phi(T[phi^(-1)(S)]) = T'[phi(phi^(-1)(S))] = T'[S]$

Let's show that if $T prop T'$ then $forall S,S' in cal(S)(T), T[S] equiv T[S'] => T'[phi(S)] equiv T'[phi(S')]$, by induction on $T prop T'$. This is exactly the injectivity (but invert $T, T'$ and $phi^(-1)$ but it's the same).

- If $T= () = T'$, then it is true.
- If $T = x(x_1,...,x_n)$ and $T' = x'(x'_1,...,x'_n)$ with $forall i, T(x_i) prop_(phi_(|T(x_i))) T'(x'_i)$.

  Since $T[S] equiv T[S']$, denote $x_(a_1),...,x_(a_k)$ (resp. $x_(b_1),...,x_(b_k)$) the children of the root in $T[S]$ (resp. $T[S']$), we have $forall i <= k, x_(a_i) equiv x_(b_i)$

  Then since we are in case 2 of $prop_phi$, the children of $T[phi(S)]$ (resp. $T[phi(S')]$) are $(x'_(a_1),...,x'_(a_k))$ (resp. $(x'_(b_1),...,x'_(b_k))$).

  For all $i <= k$ we therefore have
  $ T'(y_(a_i)) prop_(phi^(-1)_(|T(x_(a_i)))) T(x_(a_i)) equiv T(x_(b_i)) prop_(phi_(|T(x_(a_i)))) T'(y_(b_i)) $

  Therefore....???


#pagebreak()
