#let arr = $scripts(->)$
#let arrr = $scripts(<-)$
#let AI = $"AI"$

= Definitions

Denote $Lambda$ the set of all lambda terms and $arr_beta$ the beta reduction. We define a rewrite system as a couple $(V,E)$ of verticices and $E subset.eq V^2$ the rewrite rules. It's basically an ordered graph. We denote by $C chevron x chevron.r $ the hole context $C$. We therefore have that $arr_beta$ is the set of the form $ C chevron.l (lambda x. e ) e' chevron.r arr_beta C chevron.l e[x <- e'] chevron.r $

Let $Lambda_I$ be the set of identity-terms generated by the grammar $e, e' ::= (lambda x. x) | e space e'$. It is a subset of all the lambda terms. One can see that $Lambda_I$ is closed under $arr_beta$, with $arr_beta$ being in this case of the form 
$ C chevron.l I e chevron.r arr_beta C chevron.l e chevron.r $

Let $cal(L)_I$ be the set of words on $Sigma = {A,I}$ generated by the grammar $cal(G) : w, w' ::= I | A w w'$. We define a re-write system $(cal(L)_I,arr_AI)$ with the re-write rule "we can remove a occurence of the factor $AI$", formally :
$ w A I w' arr_AI w w' $
*Remark* The set $cal(L)_I$ is very close to the set of Dyck words. We indeed have the following characterisation
$ cal(L)_I = { w in Sigma^* | |w|_A = |w|_I -1 "and" forall w' "prefix strict of" w, |w'|_A >= |w'|_I }$


This gives us that :
- All words are of odd length
- The only normal form is $I$
- All words of length $> 1$ start with an $A$
- The grammar of $cal(L)_I$ is not ambiguous (the classical proof for the Dyck's words work, just with a -1)

*Proof of the characterisation* Denote $D^o$ the characterisation set. By induction, it is clear that $cal(L)_I subset.eq D^o$. Let's prove the other inclusion by induction on the length of the word. Let $w := w_1...w_n in D^o$. If $w_1 = I$, then $w = I in cal(L)_I$. Otherwise, $w_1 = A$ and let $i$ be the first natural such than $|w_2 ... w_i|_A = |w_2 ... w_i|_I -1$. Denote $u = w_2 ... w_i$ and $v = w_(i+1) ... w_n$. Then one can quickly check that $u,v in D^o$ and we have $w = A u v in cal(L)_I$ as $u,v in cal(L)_I$ by induction.

*Proof of the non-ambigueity of $cal(G)$*
Take a word $w$ of minimal length that can be written in two different way. Then $w != I$, so $w = A u_1 u_2 = A v_1 v_2$. By minimality of the length, $|u_1| != |v_1|$, so suppose without loss of generality $|u_1| < |v_1|$ (the other way is symmetric). Then $u_1$ is a prefix of $v_1$ with $|u_1|_A = |u_1|_I - 1$, a contradiction.


#pagebreak()

== Main Theorem : $(Lambda_I, arr_beta)$ is isomorphic to $(cal(L)_I,arr_AI)$

*Proof* Let $Phi : Lambda_"I" --> cal(L)_"I"$ be the bijection defined as
$ 
Phi((lambda x.x)) &= I \
Phi(e space e') &= A space Phi(e) space Phi(e') \
$

It is a bijection because both grammars are non-ambigueous.

*Lemma* Let's first prove that for all $C$ a $Lambda_I$-context, there exists $u,v in Sigma^*$ with $u I v in cal(L)_I$ such than
$ forall e in Lambda_I, Phi(C chevron e chevron.r) = u Phi(e) v $
And that reciprocly, for all $u,v in Sigma^*$ with $u I v in cal(L)_I$, there exists a $C$ satisfying the above condition.

The intuition is that the correct notion for a "context" in our grammar $cal(L)_I$ is a pair of words of the form $u, v$ with $u I v in cal(L)_I$, the the same way that $C chevron I chevron.r in Lambda_I$.

For the forward way, by induction on $C$, there are 3 cases:
  - if $C = chevron chevron.r$ then let $u,v := epsilon$. We indeed have $epsilon I epsilon = I in cal(L)_I$
  - if $C = a C'$ then we apply our induction hypothesis on $Phi(C' chevron e chevron.r)$ to get $u',v'$ and let $u := A Phi(a) u'$ and $v' := v$. We then have $u I v = A space Phi(a) space u' I v' in cal(L)_I$. 
  - if $C = C' a$ then we apply our induction hypothesis on $Phi(C' chevron e chevron.r)$ to get $u',v'$ and let $u := A u'$ and $v := v' Phi(a) $. We then have $u I v = A space u' I v' space Phi(a) in cal(L)_I$

For the reciprocical way, by induction on $|u| + |v|$, there are 2 cases :
- if $|u| + |v| = 0$ then $C = chevron chevron.r$.
- Otherwise, $u I v = A u' I v$ (all words of length $>1$ start with an $A$). Since $A u' I v' in cal(L)_I$, by non-ambiguity of $cal(L)_I$ we can split $A u' I v = A w_1 w_2$ with $w_1,w_2 in cal(L)_I$. Two cases : 
  - if $|u' I| <= |w_1|$, we need to go into the left child. We write $w_1 = u' I w'_1$ with $w'_1 w_2 = v$. By induction on $u'$ and $w'_1$, we have a $C'$ such than $forall e in Lambda_I, Phi(C' chevron e chevron.r) = u' Phi(e)w'_1$. Finally, for $C = C' space Phi^(-1) (w_2)$ we have 
  $ Phi( C chevron e chevron.r ) = A Phi(C' chevron e chevron.r) w_2 = A u' Phi(e) w'_1 w_2 = u Phi(e) v $
  - if $|u' I| > |w_1|$, we need to go into the right child. We write $w_2 = w'_2 I v'$ with $w_1 w'_2 = u'$. By induction on $w'_2$ and $v'$, we have a $C'$ such than $forall e in Lambda_I, Phi(C' chevron e chevron.r) = w'_2 Phi(e)v$. Finally, for $C = Phi^(-1) (w_1) space C'$ we have 
  $ Phi( C chevron e chevron.r ) = A w_1 Phi(C' chevron e chevron.r) = A w_1 w'_2 Phi(e) v = u Phi(e) v $

/*We proove that $u I v in cal(L)_I$ by utillising the characterisation of $cal(L)_I$. First, we have $|u I v|_A = |u I v|_I - 1$ :
    $ |u I v|_A = |A Phi(e) u' I v'|_A = 1 + |Phi(e)|_A + |u' I v'|_A = |Phi(e)|_I + |u' I v'|_I - 1 = |u I v|_I - 1 $
    Secondly, let $w$ be a prefix of length $n$ of $u I v = A Phi(e) u' I v'$: 
    - if $n <= |A Phi(e)|$, then $w_2 ... w_n$ is a prefix of $Phi(e) in cal(L)_I$ so 
    $ |w|_A = 1 + |w_2...w_n|_I >= 1+ |w_2...w_n|_I -1 >= |w|_I $
    - if $|A Phi(e)| < n <= |A Phi(e)u' I|$, then $w_(|A Phi(e)|) ... w_n$ is a prefix of $u' I v'$*/

*Rest of Proof* Now, the proof is easy :
- If $e_1 arr_beta e_2$, then there exists a $e$ and a $C$ such than $e_1 = C chevron I e chevron.r and e_2 = chevron e chevron.r$, and we have by the lemma that $Phi(e_1) = u Phi(I e) v = u A I Phi(e) v$ and $Phi(e_2) = u Phi(e) v$, therefore $Phi(e_1) -> Phi(e_2)$.
- Reciprocly, if $w_1 arr_AI w_2$, then there exist $w,w'$ such than $w_1 = w A I w'$ and $w_2 = w w'$. Let $i$ be the first indice of $w'$ such than $|w'_1 ... w'_i|_A = |w'_1 ... w'_i|_I -1$, and denote $w_e = w'_1...w'_i$ and $w'_r = w'_(i+1) .... w'_(|w'|)$. Then $w' = w_e w'_r$ with $w_e in cal(L)_I$. Because $Phi$ is a bijection, there is a $e in Lambda_I$ with $w_e = Phi(e)$ and since we have $w, w'_r$, by our lemma, we have a context $C$. So finally, we have
$
  w_1 = w A I Phi(e) w'_r = w Phi(I e) w'_r = Phi( C chevron I e chevron.r) #h(20pt) "and" #h(20pt) w_2 = w Phi(e) w'_r = Phi( C chevron e chevron.r)
$
so $Phi^(-1) (w_1) arr_beta Phi^(-1) (w_2)$

#pagebreak()

== First analysis of $(cal(L)_I,arr_AI)$

Let's decompose words into a serie of maximal blocks of $(AI)^n$. That is, for $w in cal(L)_I$, we write
$ w = underbrace("A"..."A",a_1) (AI)^(mu_1) underbrace("I"..."I",i_1)underbrace("A"..."A",a_2) (AI)^(mu_2) ... (AI)^(mu_d) underbrace("I"..."I",i_d) $
such than $forall j, i_j + a_(j+1) >0$ (meaning that every $mu_j$ are as large as possible and the representation is unique)

*Remarks*
- $w arr_AI w'$ means that we decrement a $mu_j$ of $w$
- There are *no more syntaxical accidents* as if $w ->_AI w'$ in two different way means that both reductions comes from the same $AI^(mu_j)$)(to be proven)  
- $d$ is the degree of $w$ in the graph (d for degree)
- The number of reduction that are equivalent to each-other (the cardinality of a specific syntatical accident) is $mu_j$
- Removing a $AI$ from block $i$ only affect at most blocks $i-1, i$ and $i+1$
- Removing a $AI^(mu_j)$ if $mu_j = 1$ will do wierd things that depends on $a_j$ and $i_j$. For example, if $a_j = i_j = 1$ it will merge both surronding block into one of size $mu_(j-1) + 1 + mu_(j+1)$

*Use case example* Let's say we want to find find some $Lambda_I$-terms $t_1 arrr_beta t arr_beta t_2$ such than there is *not a unique* $t'$ such than $t_1 arr_beta t' arrr t_2$.

Let's write $w_t = u (AI)^(n+1) u' (AI)^(m+1) u''$ with $w_t arr_AI w_(t_1) := u (AI)^(n) u' (AI)^(m+1) u''$ and $w_t arr_AI w_(t_2) := u (AI)^(n+1) u' (AI)^(m) u''$.
One possible child of both is $u (AI)^n u' (AI)^m u''$, but if $u'$ is $"AAII"$ we can have by its deletion a merging of both components (see remarks above). So a counter example could be with $u' = "AAII"$ and $n=m=2$. We complete $u$ and $u''$ such than $u AI^2 u' AI^2 u'' in cal(L)_I$ (for example, $u = A$ and $u'' = I$ works) and have the counter example
$ "A" "AIAI" "AAII" "AIAI" "I" $

wich, back to lambda-terms, gives us
$ I ((I I) (I (I I))) arrr_beta underbrace(I\(I,"any") \(\(I I\) \(underbrace(I\(I,"any") I\)\)\)\) arr_beta I (I ((I I) (I I))) $
with *two* possible solutions :
$ I \(\(I I\) \(underbrace(I\(I,"any") I\)\)\) arr_beta I ((I I) (I I))  arrr_beta underbrace(I\(I,"any") \(\(I I\) \(I I\)\)\) $
$ I \(underbrace((I I),"this") \(I \(I I\)\)\) arr_beta I (I (I (I I))) arrr_beta I \(I \(\(underbrace((I I),"this") \(I I\)\)\) $
