#import "@preview/diagraph:0.2.5": *

#let arr = $scripts(->)$
#let arrr = $scripts(<-)$

#let cA = $cal(A)$
#let cB = $cal(B)$
#let cC = $cal(C)$
#let cN = $cal(N)$

#let DAG = math.op("DAG")

#let TODO = text(fill:red)[*TODO*]

#set document(author: ("Coda Bourotte"), title: "Internship Report")
#set page(numbering: "1/1", number-align: center)
#set text(lang: "en")
  
#{
  v(150pt)
  set text(size: 1.7em)
  align(center)[
    #block(text(weight: 700, 1.75em, [Internship Report]))
    #v(20pt)
    #block(text(1.25em, [Reduction graph of $lambda$-calculus]))
    #v(20pt)
    #block([*Coda Bourotte*\
    coda.bourotte\@ens-lyon.fr
    #v(50pt)
    Internship supervisor\
    *Giulio Manzonetto*\
    IRIF Laboratory --- Paris])
    #v(50pt)
    //#figure(image("LOGO.png", width: 50%))
  ]
  pagebreak()
}

#set heading(numbering: "1.")
#set par(justify: true)
#show outline.entry.where(
  level: 1
): it => {
  v(12pt, weak: true)
  strong(it)
}

#align(center)[
#box(inset: (left:40pt,right:40pt), [
  = Abstract
  #lorem(80)
])]

#outline(depth: 2, indent:5pt)

= Introduction

== Motivation

== Survey


== Definitions

*General* We will write a definition using the waltrus operator $:=$. Define $[k] := {1,...,k}$, $NN := {0,1,2,...}$ the set of non-negative integers and  $NN^* := NN \\ {0}$. We will denote by $cal(P)(X)$ the set of subset of $X$ and $|X|$ the cardinal of $X$. For $A,B$ two sets, we'll denote by $A^B$ the sets of function from $B$ to $A$ and by $A union.sq B$ the disjoint union of $A$ and $B$. We define $cal(P)_k (X)$ or $binom(X,k)$ to be the set of subset of cardinal $k$, and by $cal(P)_(<= k) (X)$ the set of subset of cardinal at most $k$. For $X$ a set and $n_1,...,n_k in NN$ such that $|A| = n_1 + ... + n_k$, we will denote by $binom(X,n_1,...,n_k)$ the set of partitions of the form $union.big.sq_(1<=i<= k) A_i = X$ with $|A_i| = n_i$, and by $binom(n,n_1,...,n_k) = |binom([n],n_1,...,n_k)|$. It is well known that $
binom(n,n_1,...,n_k) = (n!)/(n_1 ! n_2 ! ... n_k !)
$

*Graphs* A graph is a $G = (V,E)$ with $E subset.eq cal(P)_2(V)$, and an directed graph has $E subset.eq V^2$. Both can have multi-graph variants, where every edge $e$ is associated to an arity $\#(e) in NN^*$. For $T = (V_T,E_T,r)$ a rooted tree, denote $T(x)$ the subtree tree rooted at $x$, and by $|T|$ the number of nodes in $T$. For $G$ a graph, denote $deg v$ the degree of $v$ and if $G$ is directed, denote $deg^+ v$ the outgoing degree and $deg^- v$ the ingoing degree. If $G$ is a multi-graph, the degree is the sum of the arities. For $S subset.eq V_G$, denote by $G[S]$ the (multi)graph induced on $S$. If $G$ is a multi-graph, denote $overline(G)$ the same graph where all arities is $1$, i.e. the regular graph behind $G$. A _path_ is a sequence of vertices $chevron v_1,...,v_k chevron.r$ with $forall i < k, \#(v_i,v_(i+1))>=1$ and a _co-path_ is a sequence of vertices $chevron v_1,...,v_k chevron.r$ with $forall i < k, \#(v_(i+1),v_i)>=1$

Two graphs $(V_1,E_1)$ and $(V_2,E_2)$ are said to be isomorphic if there exists a bijection $Phi : V_1 --> V_2$ such that $(x,y) in E_1 <=> (Phi(x),Phi(y)) in E_2$ and that $Phi$ preserve the arity (i.e. $forall e in E_1, \#(e) = \#(Phi(e))$). We will denote this by $(V_1,E_1) equiv_Phi (V_2,E_2)$ or simply $(V_1,E_1) equiv (V_2,E_2)$

*Rewrite systems* A rewrite system $R = (V,arr)$ is an directed multi-graph with $E_G = (->)$. Nodes $v in V$ such that $deg^+ v = 0$ are called _final nodes_ or _normal forms_, and nodes such that $deg^- v = 0$ are call initial nodes. A walk $chevron.l p_1,...,p_n chevron.r$ in $G$ is called a _reduction sequence_ and is noted $p_1 -> p_2 -> ... -> p_n$ or $p arr^n p_n$. We denote by $arr^*$ the transitive reflexive closure of $->$.

Two rewrite system are said to be isomorphic if their respective graphs are.

*Grammars* For $cal(G)$ a grammar, denote $cal(G) chevron chevron.r$ the set of contexes over $cal(G)$. For $C$ a context denote $C chevron N chevron.r$ the context where the hole has been replaced with $N$.

*$lambda$-calculus* Let $cal(V)$ be an infinite countable set of variables. Define $Lambda$ the set of all $lambda$-terms generated by the grammar $M, N ::= x | M N | lambda x. M$ for $x in cal(V)$.

We define by induction the set of _free variables_ (denoted $"FV"(M)$) with 
- $"FV"(x) = {x}$
- $"FV"(lambda x.M) = "FV"(M) \\ {x}$
- $"FV"(M N) = "FV"(M) union "FV"(N)$

A term $M in Lambda$ is said to be _closed_ if $"FV"(M) = emptyset$. We will denote $Lambda^o$ the set of closed terms.

We define $I := lambda x.x$, $Delta := lambda x. x x$ and $Omega := Delta Delta$. For $M$ a term and $n in NN^*$, denote by $M^((n))$ the iterative application of $M$, formally defined with $M^((1)) := M$ and $M^((n+1)) := M^((n)) M$

*Identity Terms* Let $Lambda_I$ be the set of identity-terms generated by the grammar $ M,N ::= (lambda x. x) | M space N' $. It is a subset of all the lambda terms. One can see that $Lambda_I$ is closed under $arr_beta$, with $arr_beta$ being in this case of the form 
$ C chevron.l I e chevron.r arr_beta C chevron.l e chevron.r $

== Reduction Graphs

*Reduction Graphs* Given $M in Lambda$, we define its _reduction graph_, denoted $G_M$, as the graph $ G_M = (V_M ,E_M)$ defined with :
- $V_M = {N in Lambda | M arr_beta N }$ 
- $E_M = {(N,N') in V_M | N arr_beta N' }$

Our goal will be to characterise and capture the reduction graphs of $lambda$-terms.
Given $M in Lambda$, we define (co)-inductively its _reduction tree_, denoted $T_M$ as the tree with $M$ as a root, with children ${T_N : M arr_beta N}$.

*Remarks*
- $T_M$ is the tree of all walks over $G_M$ starting from $M$. 
- In a reduction graph $G_M$, if $N in V_M$, we have $deg_+(N)$ that is the number of redexes of $N$, and is therefore always finite.

*Classes* We define by $cC_Lambda$, $cC_(Lambda^o)$ and $cC_(Lambda_I)$ respecively the classes of reduction graphs of $Lambda$, $Lambda^o$ and $Lambda_I$ respectively. Formally, for $L = {Lambda, Lambda^o, Lambda_I}$ we have $cC_L = { G_M : M in L }$

All classes are up to ismophism : we "forget" about the label on the vertices of a graph in a class.

*Remarks* We have $cC_(Lambda_I) subset.eq cC_(Lambda^o) subset.eq cC_Lambda$

*Theorem* For any variable $x in cal(V)$, for any $M in Lambda$, we have $G_M equiv G_(lambda x. M)$

*Corollary* We therefore have (up to isomorphism) $cC_(Lambda^o) = cC_Lambda$
 - By the above remark $cC_(Lambda^o) subset.eq cC_Lambda$
 - For a $M in Lambda$, write $"FV"(M) = {x_1,...,x_n}$. We can just apply the above property on every $x_i$ to have that
  $lambda x_1...lambda x_n M$ have the same reduction graph as $M$

= General theorems

Before showing general theorems about the classes $cC_Lambda$ and $cC_(Lambda_I)$, we give a few examples of graphs that are in both classes

== Existing graphs

*Finite Paths* For all $n in NN$, the path of length $n$ denoted $P_n$ is in $cC_(Lambda_I)$. To see that, consider $I^((n+1))$. Since the only reduction of $I^((n+1))$ is $I^((n))$, we have $G_(I^((n+1)))$ that is the path of length $n$:  $ I^((n+1)) arr_beta I^((n)) arr_beta ... arr_beta I. $

*Product* For $G,G'$ two graphs, we define its product graph $G times G' = (V_(G times G'), E_(G times G'))$ by $V_(G times G') = V_G times V_(G')$ and $E_(G times G')$ the set of transition of the form $(M_1,N) -> (M_2,N)$ for $(M_1,M_2) in G_M$ or of the form $(M,N_1) -> (M,N_2)$ for $(N_1,N_2) in G_N$. 

Then, if $G_M, G_N in cC_Lambda$ (respecively $cC_(Lambda^o)$), we have $G_M times G_N in cC_Lambda$ (respecively $cC_(Lambda^o)$). For that, if $M,N$ are two terms of $Lambda$ (resp. $Lambda^o$) such than $G_M = G$ and $G_N = G'$, we have $C := lambda x. x M N$ that have for graph $G_C = G times G'$. This is because to a pair $(M',N') in G times G'$ we can map the term $lambda x. x M' N' in G_C$ and we indeed have that $lambda x. x M_1 N_2 arr_beta lambda x. x M_2 N_2$ iff either $M_1 arr_beta M_2$ and $N_1 = N_2$ or if $M_1 = M_2$ and $N_1 arr_beta N_2$

*Corollary* The $d$-dimentional grids $(n_1 times ... times n_k)$ are graphs in $cC_(Lambda^o)$. We can just apply the graph product of paths of length $n_1,...,n_k$ respecively. 

*Infinite Path* We prove that the infinite path $P_omega$ is in $cC_(Lambda^o)$. 

For that, define $Delta_3 = lambda x. (x x) x$, and consider $(Delta_3^((3))) = (Delta_3 Delta_3) Delta_3$. Then for every $n in NN$ we can map an integer $n in NN$ to $Delta_3^((n+3))$. For every $n in NN$, the only reduction of $Delta_3^((n+3))$ is to $Delta_3^((n+4))$, so we have the infinite path 
$ Delta_3^((3)) arr_beta Delta_3^((4)) arr_beta Delta_3^((5)) arr_beta ... $

*Infinite Grid* A corollary of the stability under product and the existence of the infinite path is the existence for all $d in NN^*$ of the infinite grid $NN^d$. We show a different construction that is purely using the combinator $Delta_3$ :

For that, for $d in NN$, consider $ (Delta_3^((3)))^((n)) = underbrace((Delta_3 Delta_3 Delta_3) (Delta_3 Delta_3 Delta_3) ... (Delta_3 Delta_3 Delta_3),d "times"). $

For any $overline(a) = (a_1,...,a_d) in NN^d$, we can map it to the term $[overline(a)] := Delta_3^((a_1+3)) Delta_3^((a_2 + 3)) ... Delta_3^((a_d + 3))$. Notice that $overline(a)$ only has $d$ redexes : that is, the deepest one of every $Delta_3^((a_i+3))$. Since $forall i <= d, Delta_3^((a_i + 3)) arr_beta Delta_3^((a_i + 4))$, the transitions are exacly the ones of the infinite grid.

*Cycles* For all $n in NN^*$, the cycle of length $n$ denoted $C_n$ is in $cC_(Lambda^o)$.

Let $n in NN$. Consider $M := (lambda x_1 x_2 ... x_n. x_n^((n+1)))$ and $M_C = M^((n+1))$. We will show that $M_C$ has reduction graph the cycle $C_n$. For that, just notice that the only sequence of reduction from $M_C$ is :
$
  M_C = M M^((n)) arr_beta (lambda x_2 x_3...x_n. x_n^((n+1))) M_C^((n-1)) arr_beta ... arr_beta (lambda x_n. x_n^((n+1))) M -> M^((n+1)) = M_C
$
So the reduction graph of $M_C$ is a cycle of length $n$. Notice that for $n=1$, we get $C_1 = (lambda x. x x) (lambda x. x x) = Omega$ the loop.

*Corollary* The graph $(ZZ\/2ZZ)^d in Lambda$ by applying $d$ times the product property over $d$ cycles $C_2$.

== Lambda-calculus properties

*Ray* Given $G = (V,E)$ a (pottentially infinite) graph, we say that two walks $ v = (v_i)_(i in NN), u = (u_i)_(i in NN)$ _point in the same direction_ if equivalently:
- For all $F scripts(subset.eq)_f V$, ultimately $v$ and $u$ are in the same connected component in $G\\ F$.
- There exists a walk $w = (w_i)_(i in NN)$ such than $|"Im"(w) inter "Im"(u)| = infinity = |"Im"(w) inter "Im"(v)|$.
It is a equivalence relation. A _ray_ (or _direction_) is an equivalence class of this relation.

*Theorem (unique ray)* A graph is confluent iff it has a unique ray.

*Corollary* All reductions graphs of a confluent system have a unique ray.

*Infinite trees* If $T in cC_Lambda$ is a tree, then it is a path $P_n$ for $n in NN union {omega}$. This is a simple corollary of the unique ray property:
suppose by contradiction that there is a $N in G_T$ with outgoing degree $>=2$.
Then removing such a node should keep both ray starting at the two children in the same connected component, which is a constradiction as they are on diffferent branches.

== Classes it is not apart of

When considering the class $cC_Lambda$, a natural question is to ask what graph parameters are bounded in $cC_Lambda$.
For example, the number of ray is bounded by 1. Knowing the different methods in automatic model checking using tree-width, clique-width or twin-width, we will unfortunatly give example of graphs of arbitrary width in $Lambda_I$.

*Lemma 1* If $M,N in Lambda_I$, then $G_(M N)$ contains has a subgraph the product $G_M times G_N$.
To see that, let $f : G_M times G_N --> G_(M N)$ be defined with $f(M',N') |-> M' N'$. We shall prove that $G_(M N)["Im"(f)] equiv G_M times G_N$.
Let's first prove that $f$ is injective, let $f(M_1, N_1) = C_1 =f(M_2, N_2)$

Since $f$ is obvisously surjective on $"Im"(f)$, we have that $f$ is bijective. It is a 


== Typed system

= Reduction Trees of $I$-terms 
We will study the identity rewrite system $(Lambda_I, arr_beta)$, and prove that it is equivalent to a rewrite system on trees, allowing
us to use counting argument and general properties on trees.

== Equivalent systems


#let ORTrees = $bold("ORTrees")$
*Tree rewrite system* Define $ORTrees$ the set of all unlabeled rooted ordered (left-to-right) trees of unbounded degree.
We say that $T arr_l T'$ if there is a leaf $u in V_T$ such than $T - u = T'$. We define the $ORTrees$ rewrite system by $(ORTrees, arr_l)$

*Theorem* $(Lambda_I, arr_beta) equiv (ORTrees, arr_l)$

*Proof.* We define inductively the isomorphism $Phi : Lambda_I <--> ORTrees$ :
- Let $M in lambda_I$, write $M = M_1 (M_2 (M_3 ... (M_n I)))$. We then define $Phi(M)$ as the tree with one node and with children $Phi(M_1),..., Phi(M_n)$:
$ Phi(M) := N(Phi(M_1),...,Phi(M_n)) $
- Let $T in ORTrees$ with children $C_1,...,C_n$, we have
$ Phi^(-1) (T) = Phi^(-1) (C_1) space ( Phi^(-1) (C_2) space ... (Phi^(-1) (C_n)  space I)...) $

Then, let's show that it is a ismorphism of structure. Let $C chevron.l I x chevron.r arr_beta C chevron.l x chevron.r$ be a transition. Write $x = x_1 (x_2 (... (x_n I)))$. Then
$ Phi(I x) = N(Phi(I), Phi(x_1),...,Phi(x_n)) $
while
$ Phi(x) = N(Phi(x_1),...,Phi(x_n)) $
so $Phi(I x) arr_l Phi(x)$ by deleting the (leaf) child $Phi(I)$. Since $Phi$ is defined by structural recursion on the applicative structure, it is stable by contexts, hence $Phi(C chevron.l I x chevron.r) arr_l Phi(C chevron.l x chevron.r)$. Conversely, any $arr_l$ step removes a leaf child and corresponds to contracting the associated $I$-redex.

== Counting

For $T in ORTrees$, denote $cN(T)$ the number of way to reduce it into a leaf, so that $cN(T)$ is the number of path from $T$ to the empty tree, counting the multi-edges. Such a path is called a _reduction sequence_ and is represented by a sequence $chevron x_1,...,x_n chevron.r$ of vertices of $T$ such than $x_i$ is a leaf in $T[{x_(i+1),...,x_n}]$. $x_i$ represent morally the $i$-th node to be removed.

*Theorem* For all trees $T$, we have $ N(T) = (|T|!)/(product_(x in V_T) |T(x)|) $


*Proof* By induction on $|T|$. If $|T| = 1$, then there is one way, that is to remove the only node / leaf. Let us consider a tree $T$ with $|T| = n+1$. Denote the root $r$ and the direct children of the root as $x_1,...,x_d$. Let's us fist count the number of path of $T$ in function of $(cN(T(x_i)))_i$:

For all $i<= d$, let $p^((i))$ be a reduction sequence of $A_i$. Remark that for all $i in [d]$ we have $|p^((i))| = |A_i|$. For every partition $X_1 union.sq ... union.sq X_d$ of $[ n ]$ such that $|X_i| = |A_i|$ we can create the reduction sequence $p = chevron p_1,...,p_n chevron.r$ defined by induction by letting $p_(i)$ be the next element in $p^((j))$ such that $i in X_j$ (unique because it is a partition). By appending the root to $p$, we obtain a reduction sequence of $T$.

So for every $d$-uplet of reduction sequence of each children and each partionning of $[n]$ respecting the number of edges of each subtree, we can obtain a reduction sequence. This is a bijective mapping. Let $p$ be a reduction sequence. It ends with $r$, so let's ignore this node. We can extract the subsequence $p^((i))$ from splitting $p_i$ in function of which nodes occurs in which $T(x_i)$. This gives us both the partition and the set of subsequences.

We therefore arrive at this formula :

$ N(A) 
&= binom(n-1,|A_1|,...,|A_k|) product_(i=1)^k F(A_i) 
$

Then for every $i <= d$, $|T(x_i)| <= n$ so we can apply the induction hypothesis to every $T(x_i)$. Denote $n_i = |T(x_i)|$, we have :
$ 
cN(T) 
&= binom(n-1,n_1,...,n_d) product_(i=1)^k F(T(x_i)) \
&= (n-1)!/(n_ 1!...n_k !) product_(i=1)^k (n_i !)/(product_(x in T(x_i)) |T(x_i)|) \
&= (n-1)!/(product_(i=1)^k product_(x in T(x_i)) |T(x_i)|)  \
&= (n-1)!/(product_(x in V_T \\{r}) |T(x_i)|) &union.big.sq_(i<= d) T(x_i) "is a partition of" V_T \\{r}\
&= n!/(product_(x in T) |T(x_i)|) 
$


*Long chain*
#let LC = math.op("LC")
Define inductively the set of long chains of $M in Lambda_I$ as $LC(I) = emptyset$ and for $M != I$, since it can be uniquely written as 
$ M = u_1 space (u_2 space (u_3 space (....(u_d space I)))) $
we define $LC(M) = {(u_1,...,u_d)} union union.big_(i<= d)LC(u_i)$

*Corollary* For $M in lambda_I$ a identity-term, denote $|M|_I$ the number of $I$ in $M$. Then the number of way to reduce $M$ to its normal form $I$ is $ (|M|_I !)/(product_((u_1,...,u_d) in LC(M)) (1+sum_(i<= d) |u_i|_I ) ) $
= Reduction DAGs of $I$-terms
== Dyslexic Trees

*Dyslexic Transformation.* For a fixed $P subset.eq NN$, we define a tree transformation $rho_P^i (T)$ with $i$ the height by induction  :
$
rho_P^i(l) &= l " for " l " a leaf" \
rho_P^i (N(x_0,...,x_n))
  &= N(rho_P^(i+1) (x_n),...,rho_P^(i+1) (x_0)) " if " i in P \
rho_P^i (N(x_0,...,x_n))
  &= N(rho_P^(i+1) (x_0),...,rho_P^(i+1) (x_n)) " if " i in.not P
$

*Lemma* $rho_P^i$ is an involution.

*Proof.* By induction on the tree. The leaf case is trivial. For $T = N(x_0,...,x_n)$, if $i in P$, then
$
rho_P^i (T) = N(rho_P^(i+1)(x_n),...,rho_P^(i+1)(x_0)).
$
Applying $rho_P^i$ again reverses the order once more, and by induction each $rho_P^(i+1)(rho_P^(i+1)(x_j)) = x_j$. Hence we get back $N(x_0,...,x_n)$. The case $i in.not P$ is identical but without the reversal of the node itself. Therefore $rho_P^i compose rho_P^i = id$.

*Dyslexic Equivalence* We define the equivalence relation $T scripts(prop)_P T' <==> rho^0_P (T) = T'$ or simply $T prop T'$ if there exists a $P subset.eq NN$ such than $T scripts(equiv)_P T'$. It is an equivalence relation:
- *Symmetry:* If $T scripts(prop)_P T'$, then $rho_P (T') = T$ because $rho_P$ is an involution.
- *Reflexivity:* For all $T$, since  $rho_emptyset (T) = T$ we have $T prop T$.
- *Transitivity:* If $rho^0_(P') (rho^0_(P) (T)) = T'$, then $rho^0_(P xor P') (T) = T'$ with $P xor P'$ the xor (symetric difference) of $P$ and $P'$.

For $T prop T'$, there is an isomorphism as rooted unordered tree $phi_T^P : V_T <--> V_(T')$. We will omit $P$ and $T$ when it's clear from context.
$rho$ is an operation on trees while $phi$ is the operation on the nodes of a fixed tree. We can see that $T equiv T' => rho_P (T) equiv rho_P (T')$ as it is a function defined on rooted ordered trees. 

*Dyslexic $Lambda_I$* We characterise the 


*Subtrees* If $S subset.eq V_T$ is connected and contains the root, then $T[S]$ is an induced subtree.
Denote $cal(S)(T)$ the sets of such connected subset containing the root.
Morally, we removes iteratively all the leafs outside of $S$. Notice that $S |-> T[S]$ is not always injective.

*Functoriality Lemma* Let $T in ORTrees$ be an ordered tree and $S in cal(S)(T)$, then $ forall P subset.eq NN, forall i in NN, space rho^i_P (T)[ phi_P^T (S) ] equiv rho_P^i (T[S]). $

*Proof* By induction on $T$. If $T = l$ is a leaf, then necessarily $S = V_T$, hence $rho_P^i (T)[phi_P^T (S)] = l = rho_P^i (T[S]).$
Suppose now $T = N(x_0,...,x_n).$ For every $0 <= i <= n$, let $S_i = S inter V_(x_i).$ Since $S$ is connected and contains the root, every $S_i$ is either empty or belongs to $cal(S)(x_i)$. Assume first that $0 in.not P$. Then $rho_P^0(T) = N( rho_P^1(x_0),..., rho_P^1(x_n))$.

Restricting to the vertices of $phi_P^T (S)$ keeps exactly the children corresponding to non-empty $S_i$. Therefore
$
rho_P^0 (T)[phi_P^T (S)]
=
N( (rho_P^1(x_i)[phi_P^(x_i)(S_i)] )_i ).
$

By induction hypothesis, we have for each $i$ the fact that $rho_P^1(x_i)[phi_P^(x_i)(S_i)] equiv rho_P^1(x_i [S_i]).$ Hence, since the root is in $S$ and not in $P$
$
rho_P^0(T)[phi_P^T (S)] equiv N(( rho_P^1(x_i [S_i]) )_i) equiv rho_P^0 (N((x_i [S_i])_i)) equiv rho_P^0(T[S]).
$

The case $0 in P$ is identical, except that both sides reverse the order of the children simultaneously: we have
$
rho_P^0 (T)[phi_P^T (S)]
=
N( (rho_P^1(x_(n-i))[phi_P^(x_(n-i))(S_i)] )_i ).
$
and therefore
$
rho_P^0(T)[phi_P^T (S)] equiv N(( rho_P^1(x_(n-i) [S_(n-i)]) )_i) equiv rho_P^0 (N((x_i [S_i])_i)) equiv rho_P^0(T[S]).
$

*Corollary* For all $S,S' in cal(S)(T)$ such than $T[S] equiv T[S']$, we have
$ forall P subset.eq NN, space rho^0_P (T)[phi_P^T (S)] equiv rho^0_P (T)[phi_P^T (S')] $
The proof is that since  $T[S] equiv T[S']$, we have $rho^0_P (T[S]) equiv rho^0_P (T[S'])$ so by the functoriality lemma:
$ rho^0_P (T)[phi_P^T (S)] equiv rho_P^0 (T[S]) equiv rho_P^0 (T[S']) equiv rho^0_P (T)[phi_P^T (S')]. $


*Theorem* If $T prop T'$, then $DAG(T) equiv DAG(T')$.

*Proof* Suppose $rho^0_P (T) = T'$. Define the isomorphism :
$
Phi : DAG(T) &<--> &DAG(T') \
T[S] &mapsto.long &rho^0_P (T[S])
$

This is well-defined by the naturality lemma. Since $rho_P^0$ is an involution, the same construction applied from
$T'$ to $T$ gives the inverse map, so we have that $Phi$ is bijective.

Now we show that $Phi$ preserves edges. Since $Phi$ is involutive, we just need to proove that if $A_1 -> A_2$ is an edge in $DAG(T)$ with multiplicity $m$, then $Phi(A_1) -> Phi(1_2)$ is an edge in $DAG(T')$ with multiplicity $m' >= m$.

Suppose that there is an edge $A_1 -> A_2$ in $DAG(T)$ with multiplicity $m$. Then there is $m$ ways to write $A_1 equiv T[S],A_2 equiv T[S']$ where $S' = S - {l}$ for some leaf $l$ of $T[S]$. Denote $M$ the set of couples $(S,l)$ such than $A_1 equiv T[S]$ and $A_2 equiv T[S \\ {l}]$.

Let $(S,l) in M$. Because $phi$ is a rooted tree isomorphism, $phi(l)$ is a leaf of $T'[phi(S)]$. Also, $phi(S \\ {l}) = phi(S) - {phi(l)}$. Therefore there is an edge $T'[phi(S_1)] -> T'[phi(S_2)]$. It remains to check multiplicities. 

Consider the map $gamma :(S,l) |-> (phi(S), phi(l))$. It is injective as $phi$ is. So edge multiplicities are preserved.

Therefore $DAG(T) equiv DAG(T').$

*Corollary* Let $M,N in Lambda_I$. Then if $M prop N$ then $DAG(M) = DAG(N)$.

== Generalizing by a Categorical Approch


Let's define the category $ORTrees$ whose objects are Ordered (left-to-right) Rooted Trees. We'll denote the root as $r$. We define the morphisms $ORTrees(T,T') = {S in cal(S)(T) | T[S] equiv T'}$. We say that a morphism $S in ORTrees(T,T')$ is elementary if $|V_T - S| = 1$ (aka we only remove a single node, a leaf)

*Remarks*
- There is a terminal object, the tree with only a root, with only morphisms $S = {r}$

*Theorem* Let $F : ORTrees --> ORTrees$ be an equivalence of categories. Then
$
  F(T) equiv T' => DAG(T) equiv DAG(T').
$

*Remark* The previous case was just $F(T) = rho_P (T)$ and $F(T ->_S T') = rho_P (T) -->_(phi_P (S)) rho_P (T')$ 

*Proof.* Since $F$ is an equivalence of categories, it is fully faithful and essentially
surjective. In particular, for all trees $A,B$, the map
$
  F_(A,B) : ORTrees(A,B) --> ORTrees(F(A),F(B))
$
is a bijection. We can define $Phi : DAG(T) --> DAG(F(T))$ as $Phi(T') = F(T')$ : it is indeed a application into $"DAG"(T)$ as for all $A in DAG(T)$, we have a morphism $T -->_S A in ORTrees(T,A)$, so a morphism $F(T) -->_(F(S)) F(A) in ORTrees(F(T),F(A))$, so $A in DAG(F(T))$.

Conversely, because $F$ is an equivalence, it has a quasi-inverse $G$. Applying
the same argument to $G$, every vertex of $DAG(T')$ is equivalent to some
$F(A)$ with $A$ a vertex of $DAG(T)$. Hence $Phi$ is a bijection on vertices,
up to $equiv$.

It remains to prove that $Phi$ preserves edges and their multiplicities. This is because a morphism $f : A --> B$ removes exactly one leaf if and only if $f$ is
non-invertible and irreducible (A simple cardinality argument on $S$ in $A -->_S B$ for both ways). Since equivalences of categories preserve and reflect isomorphisms, factorisations,
and irreducibility, every distinct edge of $DAG(T)$ is sent to a distinct edge $F(A) --> F(B)$ of $DAG(T')$. Thus edge multiplicities are preserved.

So $Phi : A |-> F(A)$ induces an isomorphism of directed multigraphs and we have
$
  DAG(T) equiv DAG(T').
$

*Questions!*
- Are all equivalences of categories $F : ORTrees --> ORTrees$ of the form $rho_P$ ?
- If $Psi : ORTrees --> ORTrees$ preserve the DAGs, is it necessary an equivalence of categories? Or can we lighten the hypothesis?

If both questions are yes, we have an iff with $scripts(prop)_P$. If the first is no, we should be able to get a bigger equivalence relation than $scripts(prop)_P$. If the second is false (it probably is), can we get a bigger equivalence using a $Psi$ that isn't an equivalence of categories?

== Reciprocity

